language: java
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "mv5CSM760Uv5eYkcIFXRnB2sYZFOlAQJwFq4YKx8kBl1ghvVPboj8DZG6t0nloZen+u+l8J5JZFzYIMeSHLnQnSPy+6ou4pyr7hJtRbFBaN9IH1lVcBj4vw/+M+Vltqtuhdo25Mi65gGJhBYxy9aGmTjoT+n2EE6/BXp4y0+VUs="

addons:
  coverity_scan:
    project:
      name: "konradrenner/kolabnotes-java"
      description: "Build submitted via Travis CI"
    notification_email: koni.renner@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master
